name: Run doctest
description: Just run doctest and output to Summary. Make sure the package and its dependencies are installed.
author: Kiyoon Kim

inputs:
  src-dir:
    description: Directory to search for all *.py files to run doctest.
    required: true
    default: src
  cwd:
    description: Directory to run doctest.
    required: false

runs:
  using: 'composite'
  steps:
    - shell: bash -el {0} # setup-miniconda needs this
      name: Run doctest
      run: |
        set +e  # Do not exit shell on pytest failure

        if [ -n "${{ inputs.cwd }}" ]; then
            cd ${{ inputs.cwd }}
        fi

        # if using venv, activate it.
        if [ -d .venv ]; then
            source .venv/bin/activate
        fi

        # Send both stdout and stderr to files, and also to the console
        # https://stackoverflow.com/a/53051506/7445323
        python ${{ github.action_path }}/../../scripts/run_doctest.py ${{ inputs.src-dir }} 1> >(tee stdout.txt) 2> >(tee stderr.txt >&2)
        exit_code=$?
        out=$(<stdout.txt)
        err=$(<stderr.txt)

        # Display the Markdown output in the job summary
        { echo "\`\`\`python"; echo "${out}"; echo "${err}"; echo "\`\`\`"; } > "$GITHUB_STEP_SUMMARY"

        # Exit with the exit-code returned by doctest
        exit ${exit_code}
