name: Check mkdocs build
description: Check if mkdocs build is successful. If not, try creating __init__.py files and try again.
author: Kiyoon Kim

inputs:
  requirements-docs-file:
    description: Path to the requirements_docs.txt file
    required: true
    default: deps/lock/x86_64-unknown-linux-gnu/requirements_docs.txt
  src-dir:
    description: Path to the source directory, for generating __init__.py files
    required: true
    default: src

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        pip3 install uv
        uv venv
        source .venv/bin/activate
        uv pip install -r ${{ inputs.requirements-docs-file }}

        set +e  # Do not exit shell on failure

        out=$(mkdocs build 2> stderr.txt)
        exit_code=$?
        err=$(<stderr.txt)

        # Display the raw output in the step
        echo "${out}"
        echo "${err}"

        # Display the Markdown output in the job summary
        { echo "\`\`\`python"; echo "${out}"; echo "${err}"; echo "\`\`\`"; } >> "$GITHUB_STEP_SUMMARY"

        if [[ "${exit_code}" -ne 0 ]]; then
          # If the build failed, try to generate the __init__.py file and build again
          python ${{ github.action_path }}/../../scripts/gen_init_py.py "${{ inputs.src-dir }}"
          out=$(mkdocs build 2> stderr.txt)
          new_exit_code=$?
          if [[ "${new_exit_code}" -eq 0 ]]; then
            echo "Tip: the build succeeded after generating __init__.py. Try running deargen/workflows/actions/gen-init-py." >> "$GITHUB_STEP_SUMMARY"
          fi
        fi
        exit ${exit_code}
