name: Generate __init__.py
description: Generate __init__.py files for all directories
author: Kiyoon Kim

inputs:
  src-dir:
    description: Source directory to search for directories
    deprecationMessage: Use `cwd` instead
  cwd:
    description: Directory with pyproject.toml

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [ -n "${{ inputs.cwd }}" ]; then
          cd "${{ inputs.cwd }}"
        else
          if [ -n "${{ inputs.src-dir }}" ]; then
            echo "❗ Action Required! src-dir is deprecated. Use cwd instead."
            cd "${{ inputs.src-dir }}"
          fi
        fi
        if [ ! command -v ruff &> /dev/null ]; then
          pip install ruff
        fi
        python3 ${{ github.action_path }}/../../scripts/gen_init_py.py
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "chore: generate __init__.py [skip ci]"
        git push
