name: Apply pip compile
description: Freeze dependencies using uv pip compile
author: Kiyoon Kim

inputs:
  pyproject-toml-file:
    description: Path to pyproject.toml file for getting the minimum python version
    required: true
    default: pyproject.toml
  requirements-in-dir:
    description: Directory to search all requirements*.in files
    required: true
    default: deps
  requirements-out-dir:
    description: Directory to save compiled requirements*.txt files
    required: true
    default: deps/lock
  python-platforms:
    description: Platforms to support (comma-separated)
    required: true
    default: x86_64-manylinux_2_28,aarch64-apple-darwin,x86_64-apple-darwin,x86_64-pc-windows-msvc
  cwd:
    description: 'The directory to run uv (and the whole script) in'
    required: false

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [[ -n "${{ inputs.cwd }}" ]]; then
          cd "${{ inputs.cwd }}"
        fi
        echo "min_python_version=$(python3 ${{ github.action_path }}/../../scripts/get_min_python_version.py "${{ inputs.pyproject-toml-file }}")" >> "$GITHUB_OUTPUT"
        pip3 install uv --break-system-packages
      id: get-python-version
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.get-python-version.outputs.min_python_version }}
    - shell: bash
      name: Run uv pip compile and push
      run: |
        # set +e  # Do not exit shell on failure
        if [[ -n "${{ inputs.cwd }}" ]]; then
          cd "${{ inputs.cwd }}"
        fi
        bash ${{ github.action_path }}/../../scripts/compile_requirements.sh \
          "${{ inputs.requirements-in-dir }}" \
          "${{ inputs.requirements-out-dir }}" \
          "${{ steps.get-python-version.outputs.min_python_version }}" \
          "${{ inputs.python-platforms }}"
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "build: update requirements using uv pip compile [skip ci]"
        git push
