name: (Deprecated!) Setup conda with the minimum python version, and install uv
description: Deprecated! Use setup-micromamba-and-uv instead.
author: Kiyoon Kim

inputs:
  pyproject-toml-file:
    description: Path to pyproject.toml to infer the minimum python version
    required: true
    default: pyproject.toml

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo "WARNING: This action is deprecated! Use setup-micromamba-and-uv instead." >&2
        echo "WARNING: This action is deprecated! Use setup-micromamba-and-uv instead." > "$GITHUB_OUTPUT"
        echo "python_version=$(python3 ${{ github.action_path }}/../../scripts/get_min_python_version.py ${{ inputs.pyproject-toml-file }})" >> "$GITHUB_OUTPUT"
        pip3 install --user uv --break-system-packages
      id: get-python-version
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: test
        python-version: ${{ steps.get-python-version.outputs.python_version }}
