name: (not reusable) Commit CHANGELOG.md, create a Release of this repo

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'Version tag'
        required: true
        default: v0.1.10
      dry-run:
        description: Dry run
        type: boolean
        default: false

jobs:
  commit-changelog-and-release:
    uses: ./.github/workflows/commit-changelog-and-release.yml
    with:
      version-tag: ${{ github.event.inputs.version-tag }}
      dry-run: ${{ github.event.inputs.dry-run == 'true' }}
      changelog-path: docs/CHANGELOG.md
      exclude-types: build,docs,style,other

  publish-to-pypi:
    if: ${{ github.event.inputs.dry-run == 'false' }}
    needs: commit-changelog-and-release
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version-tag }}
      - uses: deargen/workflows/actions/setup-python-and-uv@master
        with:
          pyproject-toml-file: python-projector/pyproject.toml
      - name: Build and upload to PyPI
        run: |
          cd python-projector
          uv build
          uv publish
