name: Apply ruff format, isort, and fixes

on:
  workflow_call:
    inputs:
      ruff-select:
        description: 'ruff select'
        default: I,D20,D21,UP00,UP032,UP034
        type: string
      ruff-ignore:
        description: 'ruff ignore'
        default: D212
        type: string
      ruff-version-file:
        description: The requirements.txt file that contains the Ruff version (ruff==x.x.x)
        required: true
        type: string

jobs:
  apply-ruff:
    name: Apply ruff
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install ruff
        run: |
          pip3 install -r <(grep '^ruff==' "${{ inputs.ruff-version-file }}") --break-system-packages
      - name: Run ruff and push
        run: |
          set +e  # Do not exit shell on app failure
          ruff check --select=${{ inputs.ruff-select }} --ignore=${{ inputs.ruff-ignore }} --fix --unsafe-fixes .
          ruff format .
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "style: ruff format, isort, fixes [skip ci]"
          git push
