name: Apply ruff format, isort, and fixes

on:
  workflow_call:
    inputs:
      ruff-select:
        description: 'ruff select'
        default: I,D20,D21,UP00,UP032,UP034
        type: string
      ruff-ignore:
        description: 'ruff ignore'
        type: string
      ruff-extend-ignore:
        description: 'ruff extend ignore'
        type: string
      ruff-version-file:
        description: The requirements.txt file that contains the Ruff version (ruff==x.x.x)
        required: false
        type: string
      cwd:
        description: 'The directory to run ruff in'
        required: false
        type: string

jobs:
  apply-ruff:
    name: Apply ruff
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install ruff
        run: |
          if [[ -z "${{ inputs.ruff-version-file }}" ]]; then
            pip3 install ruff --break-system-packages
          else
            pip3 install -r <(grep '^ruff==' "${{ inputs.ruff-version-file }}") --break-system-packages
          fi
      - name: Run ruff and push
        run: |
          set +e  # Do not exit shell on app failure

          if [[ -n "${{ inputs.cwd }}" ]]; then
            cd "${{ inputs.cwd }}"
          fi

          if [[ -n "${{ inputs.ruff-select}}" ]]; then
            ruff_ignore_arg=()
            if [[ -n "${{ inputs.ruff-ignore }}" ]]; then
              ruff_ignore_arg+=(--ignore '${{ inputs.ruff-ignore }}')
            fi
            ruff_extend_ignore_arg=()
            if [[ -n "${{ inputs.ruff-extend-ignore }}" ]]; then
              ruff_extend_ignore_arg+=(--extend-ignore '${{ inputs.ruff-extend-ignore }}')
            fi
            ruff check --select="${{ inputs.ruff-select }}" "${ruff_ignore_arg[@]}" "${ruff_extend_ignore_arg[@]}" --fix --unsafe-fixes .
          fi
          ruff format .
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "style: ruff format, isort, fixes [skip ci]"
          git push
